version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - "./src:/code"
    networks:
      mcloud:
        aliases:
          - mcloud-backend
    
  postgres:
    image: postgres
    restart: unless-stopped
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - "./postgres_data:/var/lib/postgresql/data"
    networks:
      mcloud:
        aliases:
          - mcloud-postgres

networks:
  mcloud:
    external: true
