version: "3"

services:
  mcloud-backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - "./src:/code/src/"
      - "./tests:/code/tests/"

  mcloud-migrations:
    build:
      context: .
      dockerfile: Dockerfile.prod
