version: "3"

services:
  mcloud-backend:
    container_name: mcloud-backend
    restart: unless-stopped
    env_file: .env
    ports:
      - "8000:8000"
    networks:
      mcloud:
        aliases:
          - mcloud-backend

  mcloud-migrations:
    container_name: mcloud-migrations
    command: alembic upgrade head
    env_file: .env
    volumes:
      - "./src:/code"
    networks:
      mcloud:
        aliases:
          - mcloud-migrations
    
  mcloud-postgres:
    container_name: mcloud-postgres
    image: postgres
    restart: unless-stopped
    env_file: .env
    volumes:
      - "./postgres_data:/var/lib/postgresql/data"
    networks:
      mcloud:
        aliases:
          - mcloud-postgres

networks:
  mcloud:
    external: true
