version: "3"

services:
  mcloud-backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    volumes:
      - "./src:/code"

  mcloud-migrations:
    build:
      context: .
      dockerfile: Dockerfile.prod
